<?php

namespace Database\Seeders;

use \App\Models\Region;
use \App\Models\Category;
use \App\Models\Commune;
use \App\Models\DeliveryOrder;
use \App\Models\Fair;
use \App\Models\NumberAddress;
use \App\Models\PaymentMethod;
use \App\Models\Permission;
use \App\Models\Product;
use \App\Models\Role;
use \App\Models\RolePermission;
use \App\Models\Stall;
use \App\Models\StreetAddress;
use \App\Models\SubCategory;
use \App\Models\ProductStall;
use \App\Models\UserStall;
use \App\Models\PurchaseOrder;
use \App\Models\UnitOfMeasure;
use \App\Models\PurchaseOrderProduct;
use \App\Models\DeliveryOrderPurchaseOrder;
use \App\Models\PaymentMethodUser;
use \App\Models\ProductUnitOfMeasure;
use \App\Models\User;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $cantidadSeeders = 30;

        /*
        Region::insert([
            ['id' => 1, 'nombreRegion' => 'I Region de Tarapaca', 'softDelete' => false, 'created_at' => now()],
            ['id' => 2, 'nombreRegion' => 'II Region de Antofagasta', 'softDelete' => false, 'created_at' => now()],
            ['id' => 3, 'nombreRegion' => 'III Region de Atacama', 'softDelete' => false, 'created_at' => now()],
            ['id' => 4, 'nombreRegion' => 'IV Region de Coquimbo', 'softDelete' => false, 'created_at' => now()],
            ['id' => 5, 'nombreRegion' => 'V Region de Valparaiso', 'softDelete' => false, 'created_at' => now()],
            ['id' => 6, 'nombreRegion' => 'VI Region del Libertador General Bernardo OHiggins', 'softDelete' => false, 'created_at' => now()],
            ['id' => 7, 'nombreRegion' => 'VII Region del Maule', 'softDelete' => false, 'created_at' => now()],
            ['id' => 8, 'nombreRegion' => 'VIII Region del Biobio', 'softDelete' => false, 'created_at' => now()],
            ['id' => 9, 'nombreRegion' => 'IX Region de La Araucania', 'softDelete' => false, 'created_at' => now()],
            ['id' => 10, 'nombreRegion' => 'X Region de Los Lagos', 'softDelete' => false, 'created_at' => now()],
            ['id' => 11, 'nombreRegion' => 'XI Region Aysen del General Carlos Ibañez del Campo', 'softDelete' => false, 'created_at' => now()],
            ['id' => 12, 'nombreRegion' => 'XII Region de Magallanes y Antartica Chilena', 'softDelete' => false, 'created_at' => now()],
            ['id' => 13, 'nombreRegion' => 'XIII Region Metropolitana de Santiago', 'softDelete' => false, 'created_at' => now()],
            ['id' => 14, 'nombreRegion' => 'XIV Region de Los Rios', 'softDelete' => false, 'created_at' => now()],
            ['id' => 15, 'nombreRegion' => 'XV Region de Arica y Parinacota', 'softDelete' => false, 'created_at' => now()],
            ['id' => 16, 'nombreRegion' => 'XVI Region de Ñuble', 'softDelete' => false, 'created_at' => now()]
        ]);
        Commune::insert([
            ['id' => 1, 'nombreComuna' => 'Alto Hospicio', 'idRegion' => 1, 'softDelete' => false, 'created_at' => now()],
            ['id' => 2, 'nombreComuna' => 'Iquique', 'idRegion' => 1, 'softDelete' => false, 'created_at' => now()],
            ['id' => 3, 'nombreComuna' => 'Camiña', 'idRegion' => 1, 'softDelete' => false, 'created_at' => now()],
            ['id' => 4, 'nombreComuna' => 'Colchane', 'idRegion' => 1, 'softDelete' => false, 'created_at' => now()],
            ['id' => 5, 'nombreComuna' => 'Tocopilla', 'idRegion' => 2, 'softDelete' => false, 'created_at' => now()],
            ['id' => 6, 'nombreComuna' => 'Mejillones', 'idRegion' => 2, 'softDelete' => false, 'created_at' => now()],
            ['id' => 7, 'nombreComuna' => 'Sierra Gorda', 'idRegion' => 2, 'softDelete' => false, 'created_at' => now()],
            ['id' => 8, 'nombreComuna' => 'Taltal', 'idRegion' => 2, 'softDelete' => false, 'created_at' => now()],
            ['id' => 9, 'nombreComuna' => 'Chañaral', 'idRegion' => 3, 'softDelete' => false, 'created_at' => now()],
            ['id' => 10, 'nombreComuna' => 'Caldera', 'idRegion' => 3, 'softDelete' => false, 'created_at' => now()],
            ['id' => 11, 'nombreComuna' => 'Tierra Amarilla', 'idRegion' => 3, 'softDelete' => false, 'created_at' => now()],
            ['id' => 12, 'nombreComuna' => 'Alto del Carmen', 'idRegion' => 3, 'softDelete' => false, 'created_at' => now()],
            ['id' => 13, 'nombreComuna' => 'La Serena', 'idRegion' => 4, 'softDelete' => false, 'created_at' => now()],
            ['id' => 14, 'nombreComuna' => 'Paihuano', 'idRegion' => 4, 'softDelete' => false, 'created_at' => now()],
            ['id' => 15, 'nombreComuna' => 'Vicuña', 'idRegion' => 4, 'softDelete' => false, 'created_at' => now()],
            ['id' => 16, 'nombreComuna' => 'Combarbalá', 'idRegion' => 4, 'softDelete' => false, 'created_at' => now()],
            ['id' => 17, 'nombreComuna' => 'Los Ándes', 'idRegion' => 5, 'softDelete' => false, 'created_at' => now()],
            ['id' => 18, 'nombreComuna' => 'Santo Domingo', 'idRegion' => 5, 'softDelete' => false, 'created_at' => now()],
            ['id' => 19, 'nombreComuna' => 'Algarrobo', 'idRegion' => 5, 'softDelete' => false, 'created_at' => now()],
            ['id' => 20, 'nombreComuna' => 'Villa Alemana', 'idRegion' => 5, 'softDelete' => false, 'created_at' => now()],
            ['id' => 21, 'nombreComuna' => 'Graneros', 'idRegion' => 6, 'softDelete' => false, 'created_at' => now()],
            ['id' => 22, 'nombreComuna' => 'Machalí', 'idRegion' => 6, 'softDelete' => false, 'created_at' => now()],
            ['id' => 23, 'nombreComuna' => 'Peumo', 'idRegion' => 6, 'softDelete' => false, 'created_at' => now()],
            ['id' => 24, 'nombreComuna' => 'Rancagua', 'idRegion' => 6, 'softDelete' => false, 'created_at' => now()],
            ['id' => 25, 'nombreComuna' => 'Linares', 'idRegion' => 7, 'softDelete' => false, 'created_at' => now()],
            ['id' => 26, 'nombreComuna' => 'Villa Alegre', 'idRegion' => 7, 'softDelete' => false, 'created_at' => now()],
            ['id' => 27, 'nombreComuna' => 'Longaví', 'idRegion' => 7, 'softDelete' => false, 'created_at' => now()],
            ['id' => 28, 'nombreComuna' => 'Parral', 'idRegion' => 7, 'softDelete' => false, 'created_at' => now()],
            ['id' => 29, 'nombreComuna' => 'Los Álamos', 'idRegion' => 8, 'softDelete' => false, 'created_at' => now()],
            ['id' => 30, 'nombreComuna' => 'Cabrero', 'idRegion' => 8, 'softDelete' => false, 'created_at' => now()],
            ['id' => 31, 'nombreComuna' => 'Los Ángeles', 'idRegion' => 8, 'softDelete' => false, 'created_at' => now()],
            ['id' => 32, 'nombreComuna' => 'Tucapel', 'idRegion' => 8, 'softDelete' => false, 'created_at' => now()],
            ['id' => 33, 'nombreComuna' => 'Temuco', 'idRegion' => 9, 'softDelete' => false, 'created_at' => now()],
            ['id' => 34, 'nombreComuna' => 'Gorbea', 'idRegion' => 9, 'softDelete' => false, 'created_at' => now()],
            ['id' => 35, 'nombreComuna' => 'Carahue', 'idRegion' => 9, 'softDelete' => false, 'created_at' => now()],
            ['id' => 36, 'nombreComuna' => 'Freire', 'idRegion' => 9, 'softDelete' => false, 'created_at' => now()],
            ['id' => 37, 'nombreComuna' => 'Ancud', 'idRegion' => 10, 'softDelete' => false, 'created_at' => now()],
            ['id' => 38, 'nombreComuna' => 'Puerto Montt', 'idRegion' => 10, 'softDelete' => false, 'created_at' => now()],
            ['id' => 39, 'nombreComuna' => 'Puerto Varas', 'idRegion' => 10, 'softDelete' => false, 'created_at' => now()],
            ['id' => 40, 'nombreComuna' => 'Osorno', 'idRegion' => 10, 'softDelete' => false, 'created_at' => now()],
            ['id' => 41, 'nombreComuna' => 'Aysén', 'idRegion' => 11, 'softDelete' => false, 'created_at' => now()],
            ['id' => 42, 'nombreComuna' => 'Tortel', 'idRegion' => 11, 'softDelete' => false, 'created_at' => now()],
            ['id' => 43, 'nombreComuna' => 'Lago Verde', 'idRegion' => 11, 'softDelete' => false, 'created_at' => now()],
            ['id' => 44, 'nombreComuna' => 'Chile Chico', 'idRegion' => 11, 'softDelete' => false, 'created_at' => now()],
            ['id' => 45, 'nombreComuna' => 'Punta Arenas', 'idRegion' => 12, 'softDelete' => false, 'created_at' => now()],
            ['id' => 46, 'nombreComuna' => 'Natales', 'idRegion' => 12, 'softDelete' => false, 'created_at' => now()],
            ['id' => 47, 'nombreComuna' => 'Torres del Paine', 'idRegion' => 12, 'softDelete' => false, 'created_at' => now()],
            ['id' => 48, 'nombreComuna' => 'Cabo de Hornos', 'idRegion' => 12, 'softDelete' => false, 'created_at' => now()],
            ['id' => 49, 'nombreComuna' => 'Santiago', 'idRegion' => 13, 'softDelete' => false, 'created_at' => now()],
            ['id' => 50, 'nombreComuna' => 'Quinta Normal', 'idRegion' => 13, 'softDelete' => false, 'created_at' => now()],
            ['id' => 51, 'nombreComuna' => 'Pudahuel', 'idRegion' => 13, 'softDelete' => false, 'created_at' => now()],
            ['id' => 52, 'nombreComuna' => 'Estación Central', 'idRegion' => 13, 'softDelete' => false, 'created_at' => now()],
            ['id' => 53, 'nombreComuna' => 'Lago Ranco', 'idRegion' => 14, 'softDelete' => false, 'created_at' => now()],
            ['id' => 54, 'nombreComuna' => 'Río Bueno', 'idRegion' => 14, 'softDelete' => false, 'created_at' => now()],
            ['id' => 55, 'nombreComuna' => 'Corral', 'idRegion' => 14, 'softDelete' => false, 'created_at' => now()],
            ['id' => 56, 'nombreComuna' => 'Valdivia', 'idRegion' => 14, 'softDelete' => false, 'created_at' => now()],
            ['id' => 57, 'nombreComuna' => 'Arica', 'idRegion' => 15, 'softDelete' => false, 'created_at' => now()],
            ['id' => 58, 'nombreComuna' => 'General Lagos', 'idRegion' => 15, 'softDelete' => false, 'created_at' => now()],
            ['id' => 59, 'nombreComuna' => 'Putre', 'idRegion' => 15, 'softDelete' => false, 'created_at' => now()],
            ['id' => 60, 'nombreComuna' => 'Camarones', 'idRegion' => 15, 'softDelete' => false, 'created_at' => now()],
            ['id' => 61, 'nombreComuna' => 'Bulnes', 'idRegion' => 16, 'softDelete' => false, 'created_at' => now()],
            ['id' => 62, 'nombreComuna' => 'Chillán', 'idRegion' => 16, 'softDelete' => false, 'created_at' => now()],
            ['id' => 63, 'nombreComuna' => 'Quillón', 'idRegion' => 16, 'softDelete' => false, 'created_at' => now()],
            ['id' => 64, 'nombreComuna' => 'Quirihue', 'idRegion' => 16, 'softDelete' => false, 'created_at' => now()]
        ]);
        StreetAddress::insert([
            ['id' => 1, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 2, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 3, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 4, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 5, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 6, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 7, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 8, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 9, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 10, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 11, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 12, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 13, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 14, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 15, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 16, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 17, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 18, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 19, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 20, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 21, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 22, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 23, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 24, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 25, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 26, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 27, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 28, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 29, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 30, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 31, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 32, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 33, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 34, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 35, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 36, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 37, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 38, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 39, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 40, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 41, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 42, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 43, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 44, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 45, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 46, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 47, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 48, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 49, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 50, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 51, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 52, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 53, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 54, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 55, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 56, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 57, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 58, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 59, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 60, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 61, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 62, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 63, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 64, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 65, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 66, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 67, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 68, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 69, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 70, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 71, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 72, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 73, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 74, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 75, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 76, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 77, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 78, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 79, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 80, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 81, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 82, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 83, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 84, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 85, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 86, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 87, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 88, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 89, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 90, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 91, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 92, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 93, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 94, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 95, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 96, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 97, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 98, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 99, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 100, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 101, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 102, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 103, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 104, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 105, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 106, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 107, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 108, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 109, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 110, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 111, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 112, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 113, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 114, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 115, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 116, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 117, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 118, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 119, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 120, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 121, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 122, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 123, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 124, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 125, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 126, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()],
            ['id' => 127, 'nombreCalle' => "Alameda", 'softDelete' => false, 'created_at' => now()],
            ['id' => 128, 'nombreCalle' => "Matucana", 'softDelete' => false, 'created_at' => now()]
        ]);
        NumberAddress::insert([
            ['id' => 1, 'numeroCalle' => "2898", 'idComuna' => '1', 'idCalle' => '1', 'softDelete' => false, 'created_at' => now()],
            ['id' => 2, 'numeroCalle' => "3015", 'idComuna' => '1', 'idCalle' => '1', 'softDelete' => false, 'created_at' => now()],
            ['id' => 3, 'numeroCalle' => "9828", 'idComuna' => '1', 'idCalle' => '2', 'softDelete' => false, 'created_at' => now()],
            ['id' => 4, 'numeroCalle' => "1540", 'idComuna' => '1', 'idCalle' => '2', 'softDelete' => false, 'created_at' => now()],
            ['id' => 5, 'numeroCalle' => "2898", 'idComuna' => '2', 'idCalle' => '3', 'softDelete' => false, 'created_at' => now()],
            ['id' => 6, 'numeroCalle' => "3015", 'idComuna' => '2', 'idCalle' => '3', 'softDelete' => false, 'created_at' => now()],
            ['id' => 7, 'numeroCalle' => "9828", 'idComuna' => '2', 'idCalle' => '4', 'softDelete' => false, 'created_at' => now()],
            ['id' => 8, 'numeroCalle' => "1540", 'idComuna' => '2', 'idCalle' => '4', 'softDelete' => false, 'created_at' => now()],
            ['id' => 9, 'numeroCalle' => "2898", 'idComuna' => '3', 'idCalle' => '5', 'softDelete' => false, 'created_at' => now()],
            ['id' => 10, 'numeroCalle' => "3015", 'idComuna' => '3', 'idCalle' => '5', 'softDelete' => false, 'created_at' => now()],
            ['id' => 11, 'numeroCalle' => "9828", 'idComuna' => '3', 'idCalle' => '6', 'softDelete' => false, 'created_at' => now()],
            ['id' => 12, 'numeroCalle' => "1540", 'idComuna' => '3', 'idCalle' => '6', 'softDelete' => false, 'created_at' => now()],
            ['id' => 13, 'numeroCalle' => "2898", 'idComuna' => '4', 'idCalle' => '7', 'softDelete' => false, 'created_at' => now()],
            ['id' => 14, 'numeroCalle' => "3015", 'idComuna' => '4', 'idCalle' => '7', 'softDelete' => false, 'created_at' => now()],
            ['id' => 15, 'numeroCalle' => "9828", 'idComuna' => '4', 'idCalle' => '8', 'softDelete' => false, 'created_at' => now()],
            ['id' => 16, 'numeroCalle' => "1540", 'idComuna' => '4', 'idCalle' => '8', 'softDelete' => false, 'created_at' => now()],

            ['id' => 17, 'numeroCalle' => "2898", 'idComuna' => '5', 'idCalle' => '9', 'softDelete' => false, 'created_at' => now()],
            ['id' => 18, 'numeroCalle' => "3015", 'idComuna' => '5', 'idCalle' => '9', 'softDelete' => false, 'created_at' => now()],
            ['id' => 19, 'numeroCalle' => "9828", 'idComuna' => '5', 'idCalle' => '10', 'softDelete' => false, 'created_at' => now()],
            ['id' => 20, 'numeroCalle' => "1540", 'idComuna' => '5', 'idCalle' => '10', 'softDelete' => false, 'created_at' => now()],
            ['id' => 21, 'numeroCalle' => "2898", 'idComuna' => '6', 'idCalle' => '11', 'softDelete' => false, 'created_at' => now()],
            ['id' => 22, 'numeroCalle' => "3015", 'idComuna' => '6', 'idCalle' => '11', 'softDelete' => false, 'created_at' => now()],
            ['id' => 23, 'numeroCalle' => "9828", 'idComuna' => '6', 'idCalle' => '12', 'softDelete' => false, 'created_at' => now()],
            ['id' => 24, 'numeroCalle' => "1540", 'idComuna' => '6', 'idCalle' => '12', 'softDelete' => false, 'created_at' => now()],
            ['id' => 25, 'numeroCalle' => "2898", 'idComuna' => '7', 'idCalle' => '13', 'softDelete' => false, 'created_at' => now()],
            ['id' => 26, 'numeroCalle' => "3015", 'idComuna' => '7', 'idCalle' => '13', 'softDelete' => false, 'created_at' => now()],
            ['id' => 27, 'numeroCalle' => "9828", 'idComuna' => '7', 'idCalle' => '14', 'softDelete' => false, 'created_at' => now()],
            ['id' => 28, 'numeroCalle' => "1540", 'idComuna' => '7', 'idCalle' => '14', 'softDelete' => false, 'created_at' => now()],
            ['id' => 29, 'numeroCalle' => "2898", 'idComuna' => '8', 'idCalle' => '15', 'softDelete' => false, 'created_at' => now()],
            ['id' => 30, 'numeroCalle' => "3015", 'idComuna' => '8', 'idCalle' => '15', 'softDelete' => false, 'created_at' => now()],
            ['id' => 31, 'numeroCalle' => "9828", 'idComuna' => '8', 'idCalle' => '16', 'softDelete' => false, 'created_at' => now()],
            ['id' => 32, 'numeroCalle' => "1540", 'idComuna' => '8', 'idCalle' => '16', 'softDelete' => false, 'created_at' => now()],

            ['id' => 33, 'numeroCalle' => "2898", 'idComuna' => '9', 'idCalle' => '17', 'softDelete' => false, 'created_at' => now()],
            ['id' => 34, 'numeroCalle' => "3015", 'idComuna' => '9', 'idCalle' => '17', 'softDelete' => false, 'created_at' => now()],
            ['id' => 35, 'numeroCalle' => "9828", 'idComuna' => '9', 'idCalle' => '18', 'softDelete' => false, 'created_at' => now()],
            ['id' => 36, 'numeroCalle' => "1540", 'idComuna' => '9', 'idCalle' => '18', 'softDelete' => false, 'created_at' => now()],
            ['id' => 37, 'numeroCalle' => "2898", 'idComuna' => '10', 'idCalle' => '19', 'softDelete' => false, 'created_at' => now()],
            ['id' => 38, 'numeroCalle' => "3015", 'idComuna' => '10', 'idCalle' => '19', 'softDelete' => false, 'created_at' => now()],
            ['id' => 39, 'numeroCalle' => "9828", 'idComuna' => '10', 'idCalle' => '20', 'softDelete' => false, 'created_at' => now()],
            ['id' => 40, 'numeroCalle' => "1540", 'idComuna' => '10', 'idCalle' => '20', 'softDelete' => false, 'created_at' => now()],
            ['id' => 41, 'numeroCalle' => "2898", 'idComuna' => '11', 'idCalle' => '21', 'softDelete' => false, 'created_at' => now()],
            ['id' => 42, 'numeroCalle' => "3015", 'idComuna' => '11', 'idCalle' => '21', 'softDelete' => false, 'created_at' => now()],
            ['id' => 43, 'numeroCalle' => "9828", 'idComuna' => '11', 'idCalle' => '22', 'softDelete' => false, 'created_at' => now()],
            ['id' => 44, 'numeroCalle' => "1540", 'idComuna' => '11', 'idCalle' => '22', 'softDelete' => false, 'created_at' => now()],
            ['id' => 45, 'numeroCalle' => "2898", 'idComuna' => '12', 'idCalle' => '23', 'softDelete' => false, 'created_at' => now()],
            ['id' => 46, 'numeroCalle' => "3015", 'idComuna' => '12', 'idCalle' => '23', 'softDelete' => false, 'created_at' => now()],
            ['id' => 47, 'numeroCalle' => "9828", 'idComuna' => '12', 'idCalle' => '24', 'softDelete' => false, 'created_at' => now()],
            ['id' => 48, 'numeroCalle' => "1540", 'idComuna' => '12', 'idCalle' => '24', 'softDelete' => false, 'created_at' => now()],

            ['id' => 49, 'numeroCalle' => "2898", 'idComuna' => '13', 'idCalle' => '25', 'softDelete' => false, 'created_at' => now()],
            ['id' => 50, 'numeroCalle' => "3015", 'idComuna' => '13', 'idCalle' => '25', 'softDelete' => false, 'created_at' => now()],
            ['id' => 51, 'numeroCalle' => "9828", 'idComuna' => '13', 'idCalle' => '26', 'softDelete' => false, 'created_at' => now()],
            ['id' => 52, 'numeroCalle' => "1540", 'idComuna' => '13', 'idCalle' => '26', 'softDelete' => false, 'created_at' => now()],
            ['id' => 53, 'numeroCalle' => "2898", 'idComuna' => '14', 'idCalle' => '27', 'softDelete' => false, 'created_at' => now()],
            ['id' => 54, 'numeroCalle' => "3015", 'idComuna' => '14', 'idCalle' => '27', 'softDelete' => false, 'created_at' => now()],
            ['id' => 55, 'numeroCalle' => "9828", 'idComuna' => '14', 'idCalle' => '28', 'softDelete' => false, 'created_at' => now()],
            ['id' => 56, 'numeroCalle' => "1540", 'idComuna' => '14', 'idCalle' => '28', 'softDelete' => false, 'created_at' => now()],
            ['id' => 57, 'numeroCalle' => "2898", 'idComuna' => '15', 'idCalle' => '29', 'softDelete' => false, 'created_at' => now()],
            ['id' => 58, 'numeroCalle' => "3015", 'idComuna' => '15', 'idCalle' => '29', 'softDelete' => false, 'created_at' => now()],
            ['id' => 59, 'numeroCalle' => "9828", 'idComuna' => '15', 'idCalle' => '30', 'softDelete' => false, 'created_at' => now()],
            ['id' => 60, 'numeroCalle' => "1540", 'idComuna' => '15', 'idCalle' => '30', 'softDelete' => false, 'created_at' => now()],
            ['id' => 61, 'numeroCalle' => "2898", 'idComuna' => '16', 'idCalle' => '31', 'softDelete' => false, 'created_at' => now()],
            ['id' => 62, 'numeroCalle' => "3015", 'idComuna' => '16', 'idCalle' => '31', 'softDelete' => false, 'created_at' => now()],
            ['id' => 63, 'numeroCalle' => "9828", 'idComuna' => '16', 'idCalle' => '32', 'softDelete' => false, 'created_at' => now()],
            ['id' => 64, 'numeroCalle' => "1540", 'idComuna' => '16', 'idCalle' => '32', 'softDelete' => false, 'created_at' => now()],

            ['id' => 65, 'numeroCalle' => "2898", 'idComuna' => '17', 'idCalle' => '33', 'softDelete' => false, 'created_at' => now()],
            ['id' => 66, 'numeroCalle' => "3015", 'idComuna' => '17', 'idCalle' => '33', 'softDelete' => false, 'created_at' => now()],
            ['id' => 67, 'numeroCalle' => "9828", 'idComuna' => '17', 'idCalle' => '34', 'softDelete' => false, 'created_at' => now()],
            ['id' => 68, 'numeroCalle' => "1540", 'idComuna' => '17', 'idCalle' => '34', 'softDelete' => false, 'created_at' => now()],
            ['id' => 69, 'numeroCalle' => "2898", 'idComuna' => '18', 'idCalle' => '35', 'softDelete' => false, 'created_at' => now()],
            ['id' => 70, 'numeroCalle' => "3015", 'idComuna' => '18', 'idCalle' => '35', 'softDelete' => false, 'created_at' => now()],
            ['id' => 71, 'numeroCalle' => "9828", 'idComuna' => '18', 'idCalle' => '36', 'softDelete' => false, 'created_at' => now()],
            ['id' => 72, 'numeroCalle' => "1540", 'idComuna' => '18', 'idCalle' => '36', 'softDelete' => false, 'created_at' => now()],
            ['id' => 73, 'numeroCalle' => "2898", 'idComuna' => '19', 'idCalle' => '37', 'softDelete' => false, 'created_at' => now()],
            ['id' => 74, 'numeroCalle' => "3015", 'idComuna' => '19', 'idCalle' => '37', 'softDelete' => false, 'created_at' => now()],
            ['id' => 75, 'numeroCalle' => "9828", 'idComuna' => '19', 'idCalle' => '38', 'softDelete' => false, 'created_at' => now()],
            ['id' => 76, 'numeroCalle' => "1540", 'idComuna' => '19', 'idCalle' => '38', 'softDelete' => false, 'created_at' => now()],
            ['id' => 77, 'numeroCalle' => "2898", 'idComuna' => '20', 'idCalle' => '39', 'softDelete' => false, 'created_at' => now()],
            ['id' => 78, 'numeroCalle' => "3015", 'idComuna' => '20', 'idCalle' => '39', 'softDelete' => false, 'created_at' => now()],
            ['id' => 79, 'numeroCalle' => "9828", 'idComuna' => '20', 'idCalle' => '40', 'softDelete' => false, 'created_at' => now()],
            ['id' => 80, 'numeroCalle' => "1540", 'idComuna' => '20', 'idCalle' => '40', 'softDelete' => false, 'created_at' => now()],

            ['id' => 81, 'numeroCalle' => "2898", 'idComuna' => '21', 'idCalle' => '41', 'softDelete' => false, 'created_at' => now()],
            ['id' => 82, 'numeroCalle' => "3015", 'idComuna' => '21', 'idCalle' => '41', 'softDelete' => false, 'created_at' => now()],
            ['id' => 83, 'numeroCalle' => "9828", 'idComuna' => '21', 'idCalle' => '42', 'softDelete' => false, 'created_at' => now()],
            ['id' => 84, 'numeroCalle' => "1540", 'idComuna' => '21', 'idCalle' => '42', 'softDelete' => false, 'created_at' => now()],
            ['id' => 85, 'numeroCalle' => "2898", 'idComuna' => '22', 'idCalle' => '43', 'softDelete' => false, 'created_at' => now()],
            ['id' => 86, 'numeroCalle' => "3015", 'idComuna' => '22', 'idCalle' => '43', 'softDelete' => false, 'created_at' => now()],
            ['id' => 87, 'numeroCalle' => "9828", 'idComuna' => '22', 'idCalle' => '44', 'softDelete' => false, 'created_at' => now()],
            ['id' => 88, 'numeroCalle' => "1540", 'idComuna' => '22', 'idCalle' => '44', 'softDelete' => false, 'created_at' => now()],
            ['id' => 89, 'numeroCalle' => "2898", 'idComuna' => '23', 'idCalle' => '45', 'softDelete' => false, 'created_at' => now()],
            ['id' => 90, 'numeroCalle' => "3015", 'idComuna' => '23', 'idCalle' => '45', 'softDelete' => false, 'created_at' => now()],
            ['id' => 91, 'numeroCalle' => "9828", 'idComuna' => '23', 'idCalle' => '46', 'softDelete' => false, 'created_at' => now()],
            ['id' => 92, 'numeroCalle' => "1540", 'idComuna' => '23', 'idCalle' => '46', 'softDelete' => false, 'created_at' => now()],
            ['id' => 93, 'numeroCalle' => "2898", 'idComuna' => '24', 'idCalle' => '47', 'softDelete' => false, 'created_at' => now()],
            ['id' => 94, 'numeroCalle' => "3015", 'idComuna' => '24', 'idCalle' => '47', 'softDelete' => false, 'created_at' => now()],
            ['id' => 95, 'numeroCalle' => "9828", 'idComuna' => '24', 'idCalle' => '48', 'softDelete' => false, 'created_at' => now()],
            ['id' => 96, 'numeroCalle' => "1540", 'idComuna' => '24', 'idCalle' => '48', 'softDelete' => false, 'created_at' => now()],

            ['id' => 97, 'numeroCalle' => "2898", 'idComuna' => '25', 'idCalle' => '49', 'softDelete' => false, 'created_at' => now()],
            ['id' => 98, 'numeroCalle' => "3015", 'idComuna' => '25', 'idCalle' => '49', 'softDelete' => false, 'created_at' => now()],
            ['id' => 99, 'numeroCalle' => "9828", 'idComuna' => '25', 'idCalle' => '50', 'softDelete' => false, 'created_at' => now()],
            ['id' => 100, 'numeroCalle' => "1540", 'idComuna' => '25', 'idCalle' => '50', 'softDelete' => false, 'created_at' => now()],
            ['id' => 101, 'numeroCalle' => "2898", 'idComuna' => '26', 'idCalle' => '51', 'softDelete' => false, 'created_at' => now()],
            ['id' => 102, 'numeroCalle' => "3015", 'idComuna' => '26', 'idCalle' => '51', 'softDelete' => false, 'created_at' => now()],
            ['id' => 103, 'numeroCalle' => "9828", 'idComuna' => '26', 'idCalle' => '52', 'softDelete' => false, 'created_at' => now()],
            ['id' => 104, 'numeroCalle' => "1540", 'idComuna' => '26', 'idCalle' => '52', 'softDelete' => false, 'created_at' => now()],
            ['id' => 105, 'numeroCalle' => "2898", 'idComuna' => '27', 'idCalle' => '53', 'softDelete' => false, 'created_at' => now()],
            ['id' => 106, 'numeroCalle' => "3015", 'idComuna' => '27', 'idCalle' => '53', 'softDelete' => false, 'created_at' => now()],
            ['id' => 107, 'numeroCalle' => "9828", 'idComuna' => '27', 'idCalle' => '54', 'softDelete' => false, 'created_at' => now()],
            ['id' => 108, 'numeroCalle' => "1540", 'idComuna' => '27', 'idCalle' => '54', 'softDelete' => false, 'created_at' => now()],
            ['id' => 109, 'numeroCalle' => "2898", 'idComuna' => '28', 'idCalle' => '55', 'softDelete' => false, 'created_at' => now()],
            ['id' => 110, 'numeroCalle' => "3015", 'idComuna' => '28', 'idCalle' => '55', 'softDelete' => false, 'created_at' => now()],
            ['id' => 111, 'numeroCalle' => "9828", 'idComuna' => '28', 'idCalle' => '56', 'softDelete' => false, 'created_at' => now()],
            ['id' => 112, 'numeroCalle' => "1540", 'idComuna' => '28', 'idCalle' => '56', 'softDelete' => false, 'created_at' => now()],

            ['id' => 113, 'numeroCalle' => "2898", 'idComuna' => '29', 'idCalle' => '57', 'softDelete' => false, 'created_at' => now()],
            ['id' => 114, 'numeroCalle' => "3015", 'idComuna' => '29', 'idCalle' => '57', 'softDelete' => false, 'created_at' => now()],
            ['id' => 115, 'numeroCalle' => "9828", 'idComuna' => '29', 'idCalle' => '58', 'softDelete' => false, 'created_at' => now()],
            ['id' => 116, 'numeroCalle' => "1540", 'idComuna' => '29', 'idCalle' => '58', 'softDelete' => false, 'created_at' => now()],
            ['id' => 117, 'numeroCalle' => "2898", 'idComuna' => '30', 'idCalle' => '59', 'softDelete' => false, 'created_at' => now()],
            ['id' => 118, 'numeroCalle' => "3015", 'idComuna' => '30', 'idCalle' => '59', 'softDelete' => false, 'created_at' => now()],
            ['id' => 119, 'numeroCalle' => "9828", 'idComuna' => '30', 'idCalle' => '60', 'softDelete' => false, 'created_at' => now()],
            ['id' => 120, 'numeroCalle' => "1540", 'idComuna' => '30', 'idCalle' => '60', 'softDelete' => false, 'created_at' => now()],
            ['id' => 121, 'numeroCalle' => "2898", 'idComuna' => '31', 'idCalle' => '61', 'softDelete' => false, 'created_at' => now()],
            ['id' => 122, 'numeroCalle' => "3015", 'idComuna' => '31', 'idCalle' => '61', 'softDelete' => false, 'created_at' => now()],
            ['id' => 123, 'numeroCalle' => "9828", 'idComuna' => '31', 'idCalle' => '62', 'softDelete' => false, 'created_at' => now()],
            ['id' => 124, 'numeroCalle' => "1540", 'idComuna' => '31', 'idCalle' => '62', 'softDelete' => false, 'created_at' => now()],
            ['id' => 125, 'numeroCalle' => "2898", 'idComuna' => '32', 'idCalle' => '63', 'softDelete' => false, 'created_at' => now()],
            ['id' => 126, 'numeroCalle' => "3015", 'idComuna' => '32', 'idCalle' => '63', 'softDelete' => false, 'created_at' => now()],
            ['id' => 127, 'numeroCalle' => "9828", 'idComuna' => '32', 'idCalle' => '64', 'softDelete' => false, 'created_at' => now()],
            ['id' => 128, 'numeroCalle' => "1540", 'idComuna' => '32', 'idCalle' => '64', 'softDelete' => false, 'created_at' => now()],

            ['id' => 129, 'numeroCalle' => "2898", 'idComuna' => '33', 'idCalle' => '65', 'softDelete' => false, 'created_at' => now()],
            ['id' => 130, 'numeroCalle' => "3015", 'idComuna' => '33', 'idCalle' => '65', 'softDelete' => false, 'created_at' => now()],
            ['id' => 131, 'numeroCalle' => "9828", 'idComuna' => '33', 'idCalle' => '66', 'softDelete' => false, 'created_at' => now()],
            ['id' => 132, 'numeroCalle' => "1540", 'idComuna' => '33', 'idCalle' => '66', 'softDelete' => false, 'created_at' => now()],
            ['id' => 133, 'numeroCalle' => "2898", 'idComuna' => '34', 'idCalle' => '67', 'softDelete' => false, 'created_at' => now()],
            ['id' => 134, 'numeroCalle' => "3015", 'idComuna' => '34', 'idCalle' => '67', 'softDelete' => false, 'created_at' => now()],
            ['id' => 135, 'numeroCalle' => "9828", 'idComuna' => '34', 'idCalle' => '68', 'softDelete' => false, 'created_at' => now()],
            ['id' => 136, 'numeroCalle' => "1540", 'idComuna' => '34', 'idCalle' => '68', 'softDelete' => false, 'created_at' => now()],
            ['id' => 137, 'numeroCalle' => "2898", 'idComuna' => '35', 'idCalle' => '69', 'softDelete' => false, 'created_at' => now()],
            ['id' => 138, 'numeroCalle' => "3015", 'idComuna' => '35', 'idCalle' => '69', 'softDelete' => false, 'created_at' => now()],
            ['id' => 139, 'numeroCalle' => "9828", 'idComuna' => '35', 'idCalle' => '70', 'softDelete' => false, 'created_at' => now()],
            ['id' => 140, 'numeroCalle' => "1540", 'idComuna' => '35', 'idCalle' => '70', 'softDelete' => false, 'created_at' => now()],
            ['id' => 141, 'numeroCalle' => "2898", 'idComuna' => '36', 'idCalle' => '71', 'softDelete' => false, 'created_at' => now()],
            ['id' => 142, 'numeroCalle' => "3015", 'idComuna' => '36', 'idCalle' => '71', 'softDelete' => false, 'created_at' => now()],
            ['id' => 143, 'numeroCalle' => "9828", 'idComuna' => '36', 'idCalle' => '72', 'softDelete' => false, 'created_at' => now()],
            ['id' => 144, 'numeroCalle' => "1540", 'idComuna' => '36', 'idCalle' => '72', 'softDelete' => false, 'created_at' => now()],

            ['id' => 145, 'numeroCalle' => "2898", 'idComuna' => '37', 'idCalle' => '73', 'softDelete' => false, 'created_at' => now()],
            ['id' => 146, 'numeroCalle' => "3015", 'idComuna' => '37', 'idCalle' => '73', 'softDelete' => false, 'created_at' => now()],
            ['id' => 147, 'numeroCalle' => "9828", 'idComuna' => '37', 'idCalle' => '74', 'softDelete' => false, 'created_at' => now()],
            ['id' => 148, 'numeroCalle' => "1540", 'idComuna' => '37', 'idCalle' => '74', 'softDelete' => false, 'created_at' => now()],
            ['id' => 149, 'numeroCalle' => "2898", 'idComuna' => '38', 'idCalle' => '75', 'softDelete' => false, 'created_at' => now()],
            ['id' => 150, 'numeroCalle' => "3015", 'idComuna' => '38', 'idCalle' => '75', 'softDelete' => false, 'created_at' => now()],
            ['id' => 151, 'numeroCalle' => "9828", 'idComuna' => '38', 'idCalle' => '76', 'softDelete' => false, 'created_at' => now()],
            ['id' => 152, 'numeroCalle' => "1540", 'idComuna' => '38', 'idCalle' => '76', 'softDelete' => false, 'created_at' => now()],
            ['id' => 153, 'numeroCalle' => "2898", 'idComuna' => '39', 'idCalle' => '77', 'softDelete' => false, 'created_at' => now()],
            ['id' => 154, 'numeroCalle' => "3015", 'idComuna' => '39', 'idCalle' => '77', 'softDelete' => false, 'created_at' => now()],
            ['id' => 155, 'numeroCalle' => "9828", 'idComuna' => '39', 'idCalle' => '78', 'softDelete' => false, 'created_at' => now()],
            ['id' => 156, 'numeroCalle' => "1540", 'idComuna' => '39', 'idCalle' => '78', 'softDelete' => false, 'created_at' => now()],
            ['id' => 157, 'numeroCalle' => "2898", 'idComuna' => '40', 'idCalle' => '79', 'softDelete' => false, 'created_at' => now()],
            ['id' => 158, 'numeroCalle' => "3015", 'idComuna' => '40', 'idCalle' => '79', 'softDelete' => false, 'created_at' => now()],
            ['id' => 159, 'numeroCalle' => "9828", 'idComuna' => '40', 'idCalle' => '80', 'softDelete' => false, 'created_at' => now()],
            ['id' => 160, 'numeroCalle' => "1540", 'idComuna' => '40', 'idCalle' => '80', 'softDelete' => false, 'created_at' => now()],

            ['id' => 161, 'numeroCalle' => "2898", 'idComuna' => '41', 'idCalle' => '81', 'softDelete' => false, 'created_at' => now()],
            ['id' => 162, 'numeroCalle' => "3015", 'idComuna' => '41', 'idCalle' => '81', 'softDelete' => false, 'created_at' => now()],
            ['id' => 163, 'numeroCalle' => "9828", 'idComuna' => '41', 'idCalle' => '82', 'softDelete' => false, 'created_at' => now()],
            ['id' => 164, 'numeroCalle' => "1540", 'idComuna' => '41', 'idCalle' => '82', 'softDelete' => false, 'created_at' => now()],
            ['id' => 165, 'numeroCalle' => "2898", 'idComuna' => '42', 'idCalle' => '83', 'softDelete' => false, 'created_at' => now()],
            ['id' => 166, 'numeroCalle' => "3015", 'idComuna' => '42', 'idCalle' => '83', 'softDelete' => false, 'created_at' => now()],
            ['id' => 167, 'numeroCalle' => "9828", 'idComuna' => '42', 'idCalle' => '84', 'softDelete' => false, 'created_at' => now()],
            ['id' => 168, 'numeroCalle' => "1540", 'idComuna' => '42', 'idCalle' => '84', 'softDelete' => false, 'created_at' => now()],
            ['id' => 169, 'numeroCalle' => "2898", 'idComuna' => '43', 'idCalle' => '85', 'softDelete' => false, 'created_at' => now()],
            ['id' => 170, 'numeroCalle' => "3015", 'idComuna' => '43', 'idCalle' => '85', 'softDelete' => false, 'created_at' => now()],
            ['id' => 171, 'numeroCalle' => "9828", 'idComuna' => '43', 'idCalle' => '86', 'softDelete' => false, 'created_at' => now()],
            ['id' => 172, 'numeroCalle' => "1540", 'idComuna' => '43', 'idCalle' => '86', 'softDelete' => false, 'created_at' => now()],
            ['id' => 173, 'numeroCalle' => "2898", 'idComuna' => '44', 'idCalle' => '87', 'softDelete' => false, 'created_at' => now()],
            ['id' => 174, 'numeroCalle' => "3015", 'idComuna' => '44', 'idCalle' => '87', 'softDelete' => false, 'created_at' => now()],
            ['id' => 175, 'numeroCalle' => "9828", 'idComuna' => '44', 'idCalle' => '88', 'softDelete' => false, 'created_at' => now()],
            ['id' => 176, 'numeroCalle' => "1540", 'idComuna' => '44', 'idCalle' => '88', 'softDelete' => false, 'created_at' => now()],

            ['id' => 177, 'numeroCalle' => "2898", 'idComuna' => '45', 'idCalle' => '89', 'softDelete' => false, 'created_at' => now()],
            ['id' => 178, 'numeroCalle' => "3015", 'idComuna' => '45', 'idCalle' => '89', 'softDelete' => false, 'created_at' => now()],
            ['id' => 179, 'numeroCalle' => "9828", 'idComuna' => '45', 'idCalle' => '90', 'softDelete' => false, 'created_at' => now()],
            ['id' => 180, 'numeroCalle' => "1540", 'idComuna' => '45', 'idCalle' => '90', 'softDelete' => false, 'created_at' => now()],
            ['id' => 181, 'numeroCalle' => "2898", 'idComuna' => '46', 'idCalle' => '91', 'softDelete' => false, 'created_at' => now()],
            ['id' => 182, 'numeroCalle' => "3015", 'idComuna' => '46', 'idCalle' => '91', 'softDelete' => false, 'created_at' => now()],
            ['id' => 183, 'numeroCalle' => "9828", 'idComuna' => '46', 'idCalle' => '92', 'softDelete' => false, 'created_at' => now()],
            ['id' => 184, 'numeroCalle' => "1540", 'idComuna' => '46', 'idCalle' => '92', 'softDelete' => false, 'created_at' => now()],
            ['id' => 185, 'numeroCalle' => "2898", 'idComuna' => '47', 'idCalle' => '93', 'softDelete' => false, 'created_at' => now()],
            ['id' => 186, 'numeroCalle' => "3015", 'idComuna' => '47', 'idCalle' => '93', 'softDelete' => false, 'created_at' => now()],
            ['id' => 187, 'numeroCalle' => "9828", 'idComuna' => '47', 'idCalle' => '94', 'softDelete' => false, 'created_at' => now()],
            ['id' => 188, 'numeroCalle' => "1540", 'idComuna' => '47', 'idCalle' => '94', 'softDelete' => false, 'created_at' => now()],
            ['id' => 189, 'numeroCalle' => "2898", 'idComuna' => '48', 'idCalle' => '95', 'softDelete' => false, 'created_at' => now()],
            ['id' => 190, 'numeroCalle' => "3015", 'idComuna' => '48', 'idCalle' => '95', 'softDelete' => false, 'created_at' => now()],
            ['id' => 191, 'numeroCalle' => "9828", 'idComuna' => '48', 'idCalle' => '96', 'softDelete' => false, 'created_at' => now()],
            ['id' => 192, 'numeroCalle' => "1540", 'idComuna' => '48', 'idCalle' => '96', 'softDelete' => false, 'created_at' => now()],

            ['id' => 193, 'numeroCalle' => "2898", 'idComuna' => '49', 'idCalle' => '97', 'softDelete' => false, 'created_at' => now()],
            ['id' => 194, 'numeroCalle' => "3015", 'idComuna' => '49', 'idCalle' => '97', 'softDelete' => false, 'created_at' => now()],
            ['id' => 195, 'numeroCalle' => "9828", 'idComuna' => '49', 'idCalle' => '98', 'softDelete' => false, 'created_at' => now()],
            ['id' => 196, 'numeroCalle' => "1540", 'idComuna' => '49', 'idCalle' => '98', 'softDelete' => false, 'created_at' => now()],
            ['id' => 197, 'numeroCalle' => "2898", 'idComuna' => '50', 'idCalle' => '99', 'softDelete' => false, 'created_at' => now()],
            ['id' => 198, 'numeroCalle' => "3015", 'idComuna' => '50', 'idCalle' => '99', 'softDelete' => false, 'created_at' => now()],
            ['id' => 199, 'numeroCalle' => "9828", 'idComuna' => '50', 'idCalle' => '100', 'softDelete' => false, 'created_at' => now()],
            ['id' => 200, 'numeroCalle' => "1540", 'idComuna' => '50', 'idCalle' => '100', 'softDelete' => false, 'created_at' => now()],
            ['id' => 201, 'numeroCalle' => "2898", 'idComuna' => '51', 'idCalle' => '101', 'softDelete' => false, 'created_at' => now()],
            ['id' => 202, 'numeroCalle' => "3015", 'idComuna' => '51', 'idCalle' => '101', 'softDelete' => false, 'created_at' => now()],
            ['id' => 203, 'numeroCalle' => "9828", 'idComuna' => '51', 'idCalle' => '102', 'softDelete' => false, 'created_at' => now()],
            ['id' => 204, 'numeroCalle' => "1540", 'idComuna' => '51', 'idCalle' => '102', 'softDelete' => false, 'created_at' => now()],
            ['id' => 205, 'numeroCalle' => "2898", 'idComuna' => '52', 'idCalle' => '103', 'softDelete' => false, 'created_at' => now()],
            ['id' => 206, 'numeroCalle' => "3015", 'idComuna' => '52', 'idCalle' => '103', 'softDelete' => false, 'created_at' => now()],
            ['id' => 207, 'numeroCalle' => "9828", 'idComuna' => '52', 'idCalle' => '104', 'softDelete' => false, 'created_at' => now()],
            ['id' => 208, 'numeroCalle' => "1540", 'idComuna' => '52', 'idCalle' => '104', 'softDelete' => false, 'created_at' => now()],

            ['id' => 209, 'numeroCalle' => "2898", 'idComuna' => '53', 'idCalle' => '105', 'softDelete' => false, 'created_at' => now()],
            ['id' => 210, 'numeroCalle' => "3015", 'idComuna' => '53', 'idCalle' => '105', 'softDelete' => false, 'created_at' => now()],
            ['id' => 211, 'numeroCalle' => "9828", 'idComuna' => '53', 'idCalle' => '106', 'softDelete' => false, 'created_at' => now()],
            ['id' => 212, 'numeroCalle' => "1540", 'idComuna' => '53', 'idCalle' => '106', 'softDelete' => false, 'created_at' => now()],
            ['id' => 213, 'numeroCalle' => "2898", 'idComuna' => '54', 'idCalle' => '107', 'softDelete' => false, 'created_at' => now()],
            ['id' => 214, 'numeroCalle' => "3015", 'idComuna' => '54', 'idCalle' => '107', 'softDelete' => false, 'created_at' => now()],
            ['id' => 215, 'numeroCalle' => "9828", 'idComuna' => '54', 'idCalle' => '108', 'softDelete' => false, 'created_at' => now()],
            ['id' => 216, 'numeroCalle' => "1540", 'idComuna' => '54', 'idCalle' => '108', 'softDelete' => false, 'created_at' => now()],
            ['id' => 217, 'numeroCalle' => "2898", 'idComuna' => '55', 'idCalle' => '109', 'softDelete' => false, 'created_at' => now()],
            ['id' => 218, 'numeroCalle' => "3015", 'idComuna' => '55', 'idCalle' => '109', 'softDelete' => false, 'created_at' => now()],
            ['id' => 219, 'numeroCalle' => "9828", 'idComuna' => '55', 'idCalle' => '110', 'softDelete' => false, 'created_at' => now()],
            ['id' => 220, 'numeroCalle' => "1540", 'idComuna' => '55', 'idCalle' => '110', 'softDelete' => false, 'created_at' => now()],
            ['id' => 221, 'numeroCalle' => "2898", 'idComuna' => '56', 'idCalle' => '111', 'softDelete' => false, 'created_at' => now()],
            ['id' => 222, 'numeroCalle' => "3015", 'idComuna' => '56', 'idCalle' => '111', 'softDelete' => false, 'created_at' => now()],
            ['id' => 223, 'numeroCalle' => "9828", 'idComuna' => '56', 'idCalle' => '112', 'softDelete' => false, 'created_at' => now()],
            ['id' => 224, 'numeroCalle' => "1540", 'idComuna' => '56', 'idCalle' => '112', 'softDelete' => false, 'created_at' => now()],

            ['id' => 225, 'numeroCalle' => "2898", 'idComuna' => '57', 'idCalle' => '113', 'softDelete' => false, 'created_at' => now()],
            ['id' => 226, 'numeroCalle' => "3015", 'idComuna' => '57', 'idCalle' => '113', 'softDelete' => false, 'created_at' => now()],
            ['id' => 227, 'numeroCalle' => "9828", 'idComuna' => '57', 'idCalle' => '114', 'softDelete' => false, 'created_at' => now()],
            ['id' => 228, 'numeroCalle' => "1540", 'idComuna' => '57', 'idCalle' => '114', 'softDelete' => false, 'created_at' => now()],
            ['id' => 229, 'numeroCalle' => "2898", 'idComuna' => '58', 'idCalle' => '115', 'softDelete' => false, 'created_at' => now()],
            ['id' => 230, 'numeroCalle' => "3015", 'idComuna' => '58', 'idCalle' => '115', 'softDelete' => false, 'created_at' => now()],
            ['id' => 231, 'numeroCalle' => "9828", 'idComuna' => '58', 'idCalle' => '116', 'softDelete' => false, 'created_at' => now()],
            ['id' => 232, 'numeroCalle' => "1540", 'idComuna' => '58', 'idCalle' => '116', 'softDelete' => false, 'created_at' => now()],
            ['id' => 233, 'numeroCalle' => "2898", 'idComuna' => '59', 'idCalle' => '117', 'softDelete' => false, 'created_at' => now()],
            ['id' => 234, 'numeroCalle' => "3015", 'idComuna' => '59', 'idCalle' => '117', 'softDelete' => false, 'created_at' => now()],
            ['id' => 235, 'numeroCalle' => "9828", 'idComuna' => '59', 'idCalle' => '118', 'softDelete' => false, 'created_at' => now()],
            ['id' => 236, 'numeroCalle' => "1540", 'idComuna' => '59', 'idCalle' => '118', 'softDelete' => false, 'created_at' => now()],
            ['id' => 237, 'numeroCalle' => "2898", 'idComuna' => '60', 'idCalle' => '119', 'softDelete' => false, 'created_at' => now()],
            ['id' => 238, 'numeroCalle' => "3015", 'idComuna' => '60', 'idCalle' => '119', 'softDelete' => false, 'created_at' => now()],
            ['id' => 239, 'numeroCalle' => "9828", 'idComuna' => '60', 'idCalle' => '120', 'softDelete' => false, 'created_at' => now()],
            ['id' => 240, 'numeroCalle' => "1540", 'idComuna' => '60', 'idCalle' => '120', 'softDelete' => false, 'created_at' => now()],

            ['id' => 241, 'numeroCalle' => "2898", 'idComuna' => '61', 'idCalle' => '121', 'softDelete' => false, 'created_at' => now()],
            ['id' => 242, 'numeroCalle' => "3015", 'idComuna' => '61', 'idCalle' => '121', 'softDelete' => false, 'created_at' => now()],
            ['id' => 243, 'numeroCalle' => "9828", 'idComuna' => '61', 'idCalle' => '122', 'softDelete' => false, 'created_at' => now()],
            ['id' => 244, 'numeroCalle' => "1540", 'idComuna' => '61', 'idCalle' => '122', 'softDelete' => false, 'created_at' => now()],
            ['id' => 245, 'numeroCalle' => "2898", 'idComuna' => '62', 'idCalle' => '123', 'softDelete' => false, 'created_at' => now()],
            ['id' => 246, 'numeroCalle' => "3015", 'idComuna' => '62', 'idCalle' => '123', 'softDelete' => false, 'created_at' => now()],
            ['id' => 247, 'numeroCalle' => "9828", 'idComuna' => '62', 'idCalle' => '124', 'softDelete' => false, 'created_at' => now()],
            ['id' => 248, 'numeroCalle' => "1540", 'idComuna' => '62', 'idCalle' => '124', 'softDelete' => false, 'created_at' => now()],
            ['id' => 249, 'numeroCalle' => "2898", 'idComuna' => '63', 'idCalle' => '125', 'softDelete' => false, 'created_at' => now()],
            ['id' => 250, 'numeroCalle' => "3015", 'idComuna' => '63', 'idCalle' => '125', 'softDelete' => false, 'created_at' => now()],
            ['id' => 251, 'numeroCalle' => "9828", 'idComuna' => '63', 'idCalle' => '126', 'softDelete' => false, 'created_at' => now()],
            ['id' => 252, 'numeroCalle' => "1540", 'idComuna' => '63', 'idCalle' => '126', 'softDelete' => false, 'created_at' => now()],
            ['id' => 253, 'numeroCalle' => "2898", 'idComuna' => '64', 'idCalle' => '127', 'softDelete' => false, 'created_at' => now()],
            ['id' => 254, 'numeroCalle' => "3015", 'idComuna' => '64', 'idCalle' => '127', 'softDelete' => false, 'created_at' => now()],
            ['id' => 255, 'numeroCalle' => "9828", 'idComuna' => '64', 'idCalle' => '128', 'softDelete' => false, 'created_at' => now()],
            ['id' => 256, 'numeroCalle' => "1540", 'idComuna' => '64', 'idCalle' => '128', 'softDelete' => false, 'created_at' => now()]

        ]);
            */
        Role::insert([
            ['id' => 1, 'nombreRol' => "Comprador", 'softDelete' => false, 'created_at' => now()],
            ['id' => 2, 'nombreRol' => "Vendedor", 'softDelete' => false, 'created_at' => now()]
        ]);
        
        Fair::factory($cantidadSeeders)->create();
        Region::factory($cantidadSeeders)->create();
        Commune::factory($cantidadSeeders)->create();
        StreetAddress::factory($cantidadSeeders)->create();
        NumberAddress::factory($cantidadSeeders)->create();
        UnitOfMeasure::factory($cantidadSeeders)->create();
        Category::factory($cantidadSeeders)->create();
        Permission::factory($cantidadSeeders)->create();
        RolePermission::factory($cantidadSeeders)->create();
        SubCategory::factory($cantidadSeeders)->create();
        Product::factory(45)->create();
        ProductUnitOfMeasure::factory($cantidadSeeders)->create();
        Stall::factory($cantidadSeeders)->create();
        ProductStall::factory($cantidadSeeders)->create();
        DeliveryOrder::factory($cantidadSeeders)->create();
        User::factory($cantidadSeeders)->create();
        PaymentMethod::factory($cantidadSeeders)->create();
        UserStall::factory($cantidadSeeders)->create();
        PurchaseOrder::factory($cantidadSeeders)->create();
        PurchaseOrderProduct::factory($cantidadSeeders)->create();
        DeliveryOrderPurchaseOrder::factory($cantidadSeeders)->create();
        PaymentMethodUser::factory($cantidadSeeders)->create();
    }
}
